### PR TITLE
Function development

### PR DESCRIPTION
**Pull request by cmainov**
addition of several new functions

### CODE REVIEW

**Comment by lecy** [comment]
A few notes: 

(1) Go ahead and run the document() function to generate the package documentation for new functions. It is also a good way to test whether the code is working as expected because it will give you compiling errors or warning messages. 

Note the following three roxygen warnings below: 


```r
> devtools::document()
i Updating fiscal documentation
i Loading fiscal
Writing 'NAMESPACE'
Writing 'get_aer.Rd'
Writing 'get_arr.Rd'
Writing 'get_cr.Rd'
Writing 'get_dar.Rd'
Writing 'get_der.Rd'
Writing 'get_dgdr.Rd'
Writing 'get_dmr.Rd'
Writing 'get_doch.Rd'
Writing 'get_doci.Rd'
Writing 'get_eidr.Rd'
Writing 'get_er.Rd'
Writing 'get_ggr.Rd'
Writing 'get_iidr.Rd'
Writing 'get_lar.Rd'
Writing 'get_moch.Rd'
Writing 'get_or.Rd'
Writing 'get_per.Rd'
Writing 'get_podpm.Rd'
Writing 'get_predpm.Rd'
Writing 'get_qr.Rd'
Writing 'get_ssr.Rd'
Writing 'get_stdr.Rd'
Warning messages:
1: []8;line=42:col=1;file://C:\Users\jdlec\Dropbox (Personal)\00 - URBAN\github\fiscal\R\fiscal-health-package-doch.Rfiscal-health-package-doch.R:42]8;;] @examples has mismatched braces or quotes 
2: []8;line=4:col=1;file://C:\Users\jdlec\Dropbox (Personal)\00 - URBAN\github\fiscal\R\fiscal-health-package-doci.Rfiscal-health-package-doci.R:4]8;;] @impdocitFrom is not a known tag 
3: []8;line=66:col=1;file://C:\Users\jdlec\Dropbox (Personal)\00 - URBAN\github\fiscal\R\fiscal-health-package-doci.Rfiscal-health-package-doci.R:66]8;;] @expdocit is not a known tag 
```

(2) You can group code in files in a variety of ways. It if is a small package it's fine to have one "r-package-functions.R" file. For larger files I find it easier to separate functions so they are easy to find for editing without extensive scrolling. However, if you do this then name the files the same as function names. So get_dar() would be named: "get-dar.R" (not the use of snake case for function names and kabob case for file names). 

(3) Any functions that are internal to the package and thus not exported are often added to a "utility.R" file. For example, we only need to export the pipe operator once, so it can go there instead of repeating in every script. 

```r
###---------------------------------------------------
###   ADD PIPE OAERATOR TO THE PACKAGE
###---------------------------------------------------
#' @importFrom magrittr "%>%"

```

**Comment by cmainov** [comment]
Thanks, Jesse for these notes and your guidance! I will go ahead and work through this.

**Comment by cmainov** [comment]
Just another note: I plan on continuing to optimize the written functions to accommodate users that are using the wrangled 990 dataset you have put together and do not need to specify their own column names. We can talk about this more at this week's meeting but I have some ideas of how to go about it. Thanks.

**Comment by lecy** [comment]
Be sure to pull the most recent code. I updated file names, created a utils.R script, and removed the pipe importing from most.

**Comment by lecy** [comment]
One way to integrate the package with the data environment is to set default argument values using new variable names:

https://nonprofit-open-data-collective.github.io/irs990efile/data-dictionary/data-dictionary.html

For example,

```
function_name( assets=“F9_01_NAFB_ASSET_TOT_EOY” )
```

**Comment by cmainov** [comment]
Thanks. And yes, my plan was to go through each function description first to see  and flag which metrics can be calculated from the 990 data only or the 990 full and EZ data, set argument defaults accordingly, and then include a few conditionals at the top of the code chunk to accommodate the multiple scenarios

**Pull request merged**
